creating a fuzzing example using a calculator.
mmcgrana/gobyexample pull request #463
Opened 2023-02-28 09:10 UTC by Philip-21

I created a Fuzz example here you can look it up and see if there are changes to be made. The Fuzz function accepts inputs in binary and converts them into strings and integers then executes the inputs when the calculator function is called  .
I also want to ask how the output will be generated in the .sh file.

2023-03-01 02:09 UTC, eliben requested changes
Sorry I don't understand this example.

For fuzz testing you're supposed to write a `Fuzz*(t *testing.F)` function invoked with `go test -fuzz`. I don't see anything of the sort here.

2023-03-01 06:09 UTC, Philip-21 commented
Ok i would make changes to that.

2023-03-01 10:23 UTC, Philip-21 commented
@eliben 
In my second commit , i readjusted the code and created a test for each of the functions
The code i created here is a simple calculator .
The first function is a calculator function
 The second function sends input to the calculator function ,then  calls and executes the calculator function to display the result of the inputs.
Then for the tests 
func calculator(num1, num2 float64, operator string) having a test case of  	
func FuzzTestCalculator(f *testing.F)
and 
func InputCalculator(data float64) having a test case of 
func FuzzTestInput(f *testing.F)
I ran all tests and they Passed

2023-03-02 00:11 UTC, eliben reviewed
I think it would help if you spend some time learning how fuzz tests in Go work. Here are some good resources to review:

* https://go.dev/doc/tutorial/fuzz
* https://go.dev/security/fuzz/

2023-03-02 00:11 UTC, eliben commented on examples/fuzzing/calculator_test.go
> +func InputCalculator(data float64) float64 {
Not sure what's going on here. `InputCalculator` does not appear to be using the `data` parameter at all - what's doing the fuzzing here?

2023-03-02 11:04 UTC, Philip-21 commented
> 

Thanks i  will through the docs , i just browsed through the docs though and from what i have seen  I should use the parameters in the  InputCalculator  function so the fuzz test can be performed appropriately when its called . I will take time to read the docs and work on it

2023-03-07 17:47 UTC, Philip-21 commented on examples/fuzzing/calculator_test.go
> +
Based on the code i just pushed  , i created and utilized the []byte parameter which i converted to a []float to perform the calculations .

2023-03-07 17:53 UTC, Philip-21 commented on examples/fuzzing/calculator_test.go
> +	f.Add(b) //seed corpus inputs performed
i created testcases in []float and converted them to []bytes
then Added some seeds inputs into the fuzzCalculator(f*testing.F)

2023-03-07 17:56 UTC, Philip-21 commented on examples/fuzzing/calculator_test.go
>  }
Runs the FuzzCalculator() for  testing

2023-03-07 17:59 UTC, Philip-21 commented on examples/fuzzing/calculator_test.go
> +	f.Add(b) //seed corpus inputs performed
i created testcases in []float and converted them to []bytes
then Added some seeds inputs into the fuzzCalculator(f*testing.F)

2023-03-07 18:00 UTC, Philip-21 commented on examples/fuzzing/calculator_test.go
>  }
Runs the FuzzCalculator() for testing

2023-03-07 18:03 UTC, Philip-21 commented on examples/fuzzing/calculator_test.go
Based on the code i just pushed , i created and utilized the []byte parameter which i converted to a []float to perform the calculations . And i Performed the Calculations based on the indices of the FloatList

2023-03-07 18:04 UTC, Philip-21 commented on examples/fuzzing/calculator_test.go
> +	f.Add(b) //seed corpus inputs performed
i created testcases in []float and converted them to []bytes
then Added some seed inputs into the fuzzCalculator(f*testing.F)

2023-03-07 18:06 UTC, Philip-21 commented on examples/fuzzing/calculator_test.go
>  }
Runs the FuzzCalculator() for testing . The test case passed when i tested the code

2023-04-01 18:41 UTC, Philip-21 commented
@eliben is the code okay . Or should changes be made

2023-04-01 22:30 UTC, eliben commented
> @eliben is the code okay . Or should changes be made

No, IMHO it's not OK. The example is too complicated, and I don't think it's useful. The official go.dev tutorial at https://go.dev/doc/tutorial/fuzz has a much simpler, more comprehensible example, so the way things stand now I don't think this is useful. I also don't think this PR review is going anywhere, as there have been multiple rounds already. Perhaps fuzzing is just not a great match for gobyexample.

2023-04-01 22:30 UTC, closed without merging