link embed directive
mmcgrana/gobyexample pull request #469
Opened 2023-04-13 08:17 UTC by niyumard

2023-04-17 15:15 UTC, eliben requested changes
This seems like a good change to make - but could you please edit the source file and generate this output file?

see https://github.com/mmcgrana/gobyexample/blob/master/CONTRIBUTING.md

2023-04-19 13:35 UTC, niyumard commented
Fixed it.
I also made a trivial change to the scripts in tools folder you may want to look into.

2023-04-19 14:57 UTC, niyumard commented
Done.

2023-04-19 23:25 UTC, eliben approved these changes

2023-04-19 23:25 UTC, merged